name: PHP Lint

on:
  push:
    branches: [ "main", "action-test" ] # Specify the branches where the workflow should run
  pull_request:
    branches: [ "main", "action-test" ] # Specify the branches where the workflow should run

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' #Specify the desired PHP version

      - name: Lint PHP Files
        run: sh ./.workflows/lint-php/pre-commit